[".config/nvim"]
type = "archive"
url = "https://github.com/AstroNvim/AstroNvim/archive/refs/heads/main.zip"
exact = false
stripComponents = 1
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".local/share/fonts"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
exact = true
refreshPeriod = "168h"
include = ["*.ttf"]

[".gdbinit-gef.py"]
type = "file"
url = "https://gef.blah.cat/py"
refreshPeriod = "168h"
